import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import PageWrapper from "@/components/PageWrapper";

export const metadata: Metadata = {
  title: "TOJE AUTOS AND MERCHANDICE ",
  description: "Generated by create next app",
};

const myFont = localFont({
  src: [
    {
      path: '../fonts/Britanica-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../fonts/Britanica-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
  display: 'swap',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        <PageWrapper>
          {children}
        </PageWrapper>
      </body>
    </html>
  );
}
